version: '3.8'

services:
  # Database PostgreSQL
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: vitrine_digital
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend Node.js API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: vitrine_digital
      DB_USER: admin
      DB_PASSWORD: admin123
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/app/backend
      - /usr/app/backend/node_modules

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/app/frontend
      - /usr/app/frontend/node_modules

volumes:
  postgres_data: