version: '3.8'

services:
  # API Gateway
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3003
      - BLING_SERVICE_URL=http://bling-service:3004
      - BILLING_SERVICE_URL=http://billing-service:3005
      - BACKUP_SERVICE_URL=http://backup-service:3005
    depends_on:
      - auth-service
      - product-service
      - bling-service
      - billing-service
    networks:
      - microservices-network

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@auth-db:5432/auth_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - auth-db
      - redis
    networks:
      - microservices-network

  # Product Service
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PRODUCT_DB_HOST=product-db
      - PRODUCT_DB_PORT=5432
      - PRODUCT_DB_NAME=product_db
      - PRODUCT_DB_USER=postgres
      - PRODUCT_DB_PASSWORD=password
      - REDIS_URL=redis://redis:6379
      - CDN_ENABLED=true
      - CDN_BUCKET_NAME=${CDN_BUCKET_NAME}
      - CDN_DOMAIN_NAME=${CDN_DOMAIN_NAME}
      - CLOUDFRONT_DISTRIBUTION_ID=${CLOUDFRONT_DISTRIBUTION_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    depends_on:
      - product-db
      - redis
    networks:
      - microservices-network

  # Bling Service
  bling-service:
    build:
      context: ./bling-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@bling-db:5432/bling_db
      - REDIS_URL=redis://redis:6379
      - BLING_CLIENT_ID=${BLING_CLIENT_ID}
      - BLING_CLIENT_SECRET=${BLING_CLIENT_SECRET}
    depends_on:
      - bling-db
      - redis
    networks:
      - microservices-network

  # Billing Service
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@billing-db:5432/billing_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - billing-db
      - redis
    networks:
      - microservices-network

  # Databases
  auth-db:
    image: postgres:13
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  product-db:
    image: postgres:13
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  bling-db:
    image: postgres:13
    environment:
      POSTGRES_DB: bling_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - bling-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  billing-db:
    image: postgres:13
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - billing-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Backup Service
  backup-service:
    build:
      context: ./backup-service
      dockerfile: Dockerfile
    ports:
      - "3006:3005"
    environment:
      - NODE_ENV=development
      - BACKUP_PATH=/app/backups
      - AUTH_DB_HOST=auth-db
      - AUTH_DB_USER=postgres
      - AUTH_DB_PASSWORD=password
      - AUTH_DB_NAME=auth_db
      - PRODUCT_DB_HOST=product-db
      - PRODUCT_DB_USER=postgres
      - PRODUCT_DB_PASSWORD=password
      - PRODUCT_DB_NAME=product_db
      - BLING_DB_HOST=bling-db
      - BLING_DB_USER=postgres
      - BLING_DB_PASSWORD=password
      - BLING_DB_NAME=bling_db
      - BILLING_DB_HOST=billing-db
      - BILLING_DB_USER=postgres
      - BILLING_DB_PASSWORD=password
      - BILLING_DB_NAME=billing_db
      - BACKUP_RETENTION_DAILY=7
      - BACKUP_RETENTION_WEEKLY=4
      - BACKUP_RETENTION_MONTHLY=12
      # Opcional: AWS S3 para backup remoto
      # - AWS_S3_BUCKET=your-backup-bucket
      # - AWS_ACCESS_KEY_ID=your-access-key
      # - AWS_SECRET_ACCESS_KEY=your-secret-key
      # - AWS_REGION=us-east-1
    volumes:
      - backup-data:/app/backups
      - backup-logs:/app/logs
    depends_on:
      - auth-db
      - product-db
      - bling-db
      - billing-db
    networks:
      - microservices-network

  # Redis Message Queue
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - microservices-network

  # Monitoring (Optional)
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - microservices-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - microservices-network

volumes:
  auth-db-data:
  product-db-data:
  bling-db-data:
  billing-db-data:
  backup-data:
  backup-logs:

networks:
  microservices-network:
    driver: bridge